.\"
.TH dav1d 1 "December 2018" "0.1.0"
.SH NAME
dav1d \- fast and small AV1 video stream decoder
.SH SYNOPSIS
.B dav1d
[\fIoptions\fR]
.SH DESCRIPTION
dav1d is an AOMedia Video 1 (AV1) cross-platform decoder and focused on speed
and correctness. dav1d supports the following features: Support for all
features of the AV1 bitstream. Support for all bitdepth, 8, 10 and 12bits.
Support for all chroma subsamplings 4:2:0, 4:2:2, 4:4:4 and grayscale. Full
acceleration for AVX-2 64bits processors. Partial acceleration for SSSE3
processors. Partial acceleration for NEON processors.
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-input\fR=\fI$file\fR
input file (required)
.TP
\fB\-o\fR, \fB\-\-output\fR=\fI$file\fR
output file
.TP
\fB\-\-demuxer\fR=\fI$name\fR
force demuxer type ('ivf' or 'annexb'; default: detect from extension)
.TP
\fB\-\-muxer\fR=\fI$name\fR
force muxer type ('md5', 'yuv', 'yuv4mpeg2' or 'null'; default: detect from extension)
.TP
\fB\-q\fR, \fB\-\-quiet\fR
disable status messages
.TP
\fB\-l\fR, \fB\-\-limit\fR=\fI$num\fR
stop decoding after $num frames
.TP
\fB\-s\fR, \fB\-\-skip\fR=\fI$num\fR
skip decoding of the first $num frames
.TP
\fB\-v\fR, \fB\-\-version\fR
print version and exit
.TP
\fB\-\-framethreads\fR=\fI$num\fR
number of frame threads (default: 1)
.TP
\fB\-\-tilethreads\fR=\fI$num\fR
number of tile threads (default: 1)
.TP
\fB\-\-filmgrain\fR
enable film grain application (default: 1, except if muxer is md5)
.TP
\fB\-\-oppoint\fR=\fI$num\fR
select an operating point of a scalable AV1 bitstream (0 - 32)
.TP
\fB\-\-alllayers\fR=\fI$num\fR
output all spatial layers of a scalable AV1 bitstream (default: 1)
.TP
\fB\-\-verify\fR=\fI$md5\fR
verify decoded md5. implies --muxer md5, no output
.TP
\fB\-\-cpumask\fR=\fI$mask\fR
restrict permitted CPU instruction sets (0, 'sse2', 'ssse3', 'sse41', 'avx2' or 'avx512'; default: -1)
.TP
.SH SEE ALSO
.BR https://code.videolan.org/videolan/dav1d
