#!/bin/sh -ex

export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

gdk-pixbuf-query-loaders --update-cache

if command -v gtk-update-icon-cache; then
	gtk-update-icon-cache -q -t -f /usr/share/icons/Buuf
fi

# End of file.
