=pod

=encoding utf8

=head1 NAME

gpicview - lightweight image viewer

=head1 SYNOPSIS

B<gpicview> [I<OPTION...>] [I<FILE>]

=head1 DESCRIPTION

B<gpicview> is a lightweight GTK+ 2.x based image viewer.

=head1 OPTIONS

=head2 Application Options

=over

=item B<-v>, B<--version>

Print version and exit.

=item B<--slideshow>

Start slideshow.

=item B<--display>=I<DISPLAY>

X display to use.

=back

=head2 GTK+ Options

=over

=item B<--class>=I<CLASS>

Program class as used by the window manager.

=item B<--name>=I<NAME>

Program name as used by the window manager.

=item B<--screen>=I<SCREEN>

X screen to use.

=item B<--sync>

Make X calls synchronous.

=item B<--gtk-module>=I<MODULES>

Load additional GTK+ modules.

=item B<--g-fatal-warnings>

Make all warnings fatal.

=back

=head2 Help Options

=over

=item B<-h>, B<--help>

Show help options and exit.

=item B<--help-all>

Show all help options and exit.

=item B<--help-gtk>

Show GTK+ options and exit.

=back

=head1 AUTHORS

This manual page was written for Zeppe-Lin System by
Alexandr Savca L<mailto:alexandr.savca89@gmail.com>.

=cut
