#!/bin/sh -ex
export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

gtk-update-icon-cache -f -t /usr/share/icons/Papirus-Dark
gtk-update-icon-cache -f -t /usr/share/icons/Papirus-Light
gtk-update-icon-cache -f -t /usr/share/icons/ePapirus
gtk-update-icon-cache -f -t /usr/share/icons/Papirus

# End of file.
