#!/bin/sh -ex

export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

gtk-update-icon-cache -f -t /usr/share/icons/hicolor
update-mime-database /usr/share/mime
update-desktop-database -q
glib-compile-schemas /usr/share/glib-2.0/schemas

# End of file.
