#!/bin/sh -ex

export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
	gtk-update-icon-cache -f -t -q /usr/share/icons/hicolor
fi

if command -v update-mime-database >/dev/null 2>&1; then
	update-mime-database /usr/share/mime
fi

if command -v update-desktop-database >/dev/null 2>&1; then
	update-desktop-database -q
fi

# End of file.
