#!/bin/sh -ex
export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

if ! getent group  stunnel; then
	groupadd -r stunnel
fi

if ! getent passwd stunnel; then
	useradd -g stunnel -r -d /var/empty -s /bin/false stunnel
fi

passwd -l stunnel

# End of file.
