#!/bin/sh -ex
export PATH="/sbin:/usr/sbin:/bin:/usr/bin"
getent group  stunnel || groupadd -r stunnel
getent passwd stunnel || useradd -g stunnel -r \
	-d /var/empty -s /bin/false stunnel
passwd -l stunnel
