=pod

=encoding utf8

=head1 NAME

aft-mtp-cli - command-line client utility for MTP based devices

=head1 SYNOPSIS

B<aft-mtp-cli> [B<-vibehlVC>] [B<-f> I<file>] [B<-d> I<name>]

=head1 DESCRIPTION

B<aft-mtp-cli> is a command-line client utility for MTP based devices.

=head1 OPTIONS

=over

=item B<-v>, B<--verbose>

Show debug output.

=item B<-i>, B<--interactive>

Force interactive mode.

=item B<-b>, B<--batch>

Batch command processing.

=item B<-e>, B<--events>

Allow event processing.

=item B<-h>, B<--help>

Show help message.

=item B<-V>, B<--version>

Show version information.

=item B<-C>, B<--no-claim>

No USB interface claim.

=item B<-f>, B<--input-file> I<file>

Use I<file> to read input commands.

=item B<-d>, B<--device-name> I<name>

Use device name/model/manufacturer.

=item B<-l>, B<--device-list>

List devices.

=back

=head1 EXAMPLES

It is possible to use B<aft-mtp-cli> for automated file management.
There are two options of achieving this:

=over

=item 1.

Pass every command as B<single> command line argument:

	aft-mtp-cli "get Pictures" "cd Pictures" "ls"

If you need quoted argument for commands, you have to escape them:

	aft-mtp-cli "get \"Pictures\""

=item 2.

Pass B<-b> command line option and feed your script to stdin.

=back

=head1 SEE ALSO

L<android-file-transfer(1)>, L<aft-mtp-mount(1)>

=head1 AUTHOR

B<aft-mtp-cli> is part of B<android-file-transfer> tool written by Vladimir
Menshakov L<mailto:vladimir.menshakov@gmail.com>.

This manual page was written for Zeppe-Lin System by Alexandr Savca
L<mailto:alexandr.savca89@gmail.com>.

=cut
